---
- hosts: drupal-7
  tasks:
  - name: ensure user exists
    hsuser.js: name="{{pac}}-{{user}}" password="{{password}}" exists="true"
  - name: setup domain
    hsdomain.js: name="{{domain}}" owner="{{pac}}-{{user}}" exists="true"
  - name: download drupal tarball
    sudo: yes
    sudo_user: "{{pac}}-{{user}}"
    get_url: url=http://ftp.drupal.org/files/projects/drupal-7.41.tar.gz dest=/tmp/drupal-7.41.tgz
  - name: extract tarball
    sudo: yes
    sudo_user: "{{pac}}-{{user}}"
    command: tar -xvzf /tmp/drupal-7.41.tgz chdir="/home/pacs/{{pac}}/users/{{user}}/doms/{{domain}}/subs"
  - name: move to www
    sudo: yes
    sudo_user: "{{pac}}-{{user}}"
    command: rm -rf www chdir="/home/pacs/{{pac}}/users/{{user}}/doms/{{domain}}/subs"
  - name: move to www
    sudo: yes
    sudo_user: "{{pac}}-{{user}}"
    command: mv drupal-7.41 www chdir="/home/pacs/{{pac}}/users/{{user}}/doms/{{domain}}/subs"
  - name: ensure database exists
    hsdatabase.js: name="{{pac}}_{{user}}" password="{{password}}" instance="mysql" exists="true"
  - name: copy default.settings.php to settings.php
    sudo: yes
    sudo_user: "{{pac}}-{{user}}"
    command: cp sites/default/default.settings.php sites/default/settings.php chdir="/home/pacs/{{pac}}/users/{{user}}/doms/{{domain}}/subs/www"
  - name: change file permissions of settings.php
    sudo: yes
    sudo_user: "{{pac}}-{{user}}"
    command: chmod 666 sites/default/settings.php chdir="/home/pacs/{{pac}}/users/{{user}}/doms/{{domain}}/subs/www"
  - name: change directory permissions of sites/default
    sudo: yes
    sudo_user: "{{pac}}-{{user}}"
    command: chmod 666 sites/default chdir="/home/pacs/{{pac}}/users/{{user}}/doms/{{domain}}/subs/www"
  - name: rename .htaccess to htaccess
    sudo: yes
    sudo_user: "{{pac}}-{{user}}"
    command: mv .htaccess htaccess chdir="/home/pacs/{{pac}}/users/{{user}}/doms/{{domain}}/subs/www"
